// GENERATED by tools/roadlab-wgsl.py from proto/roadlab/rl_paint.h.
// Do not edit: regenerate. The digest below is checked by roadlab's test
// suite, so a header edit that nobody regenerated fails the build rather
// than shipping a shader that shades the road differently from the CPU.
//
// rl_paint.h digest: 2e436665007a93ce
//
// Sampler contract (paint_texture.h): the caller fills a
// var<function> array<RlBoundary, RL_MAX_BOUNDS> from the profile and style
// textures, then passes &that. Core WGSL takes a function-address-space
// pointer parameter, which is why the array is fixed-size and local.

// How many painted boundaries a station carries. Fixed because a GPU record has
// to be, and 12 because the widest cross-section in the demos paints nine. This
// is the array length WGSL needs and the cap paint_bake.h enforces — one number,
// so they cannot disagree.
const RL_MAX_BOUNDS : i32 = 12;
// Marking styles. Kept as an int rather than an enum so the value can travel
// through a float texture channel without a cast that varies by language.
const RL_MARK_NONE : i32 = 0;
const RL_MARK_SOLID : i32 = 1;
const RL_MARK_DASHED : i32 = 2;
const RL_MARK_DOUBLE : i32 = 3;
const RL_MARK_SOLID_DASHED : i32 = 4;
const RL_MARK_DASHED_SOLID : i32 = 5;
const RL_MARK_WIDE_DASHED : i32 = 6;
const RL_MARK_BOTTS : i32 = 7;
const RL_MARK_HATCH : i32 = 8;
const RL_MARK_CHEVRON : i32 = 9;
// Paint colours, as an index rather than a triple: three floats per boundary
// saved, and every backend already needs the same small palette.
const RL_PAINT_WHITE : i32 = 0;
const RL_PAINT_YELLOW : i32 = 1;
const RL_PAINT_RED : i32 = 2;
const RL_PAINT_BLUE : i32 = 3;
const RL_PAINT_GREEN : i32 = 4;

// Eight floats — two RGBA texels, or eight interpolated vertex channels.
struct RlBoundary {
  t         : f32,  // lateral offset from the reference line, IN METRES
  style     : f32,  // RL_MARK_*
  width     : f32,  // stripe width (m)
  gap       : f32,  // gap between the pair, for the double styles (m)
  dashOn    : f32,  // dash length (m)
  dashOff   : f32,  // gap length (m)
  wear      : f32,  // extra wear on this marking, over the road's own
  color     : f32,  // RL_PAINT_*
}

struct RlPaint {
  coverage  : f32,
  r         : f32,
  g         : f32,
  b         : f32,
}

struct RlRgb {
  r         : f32,
  g         : f32,
  b         : f32,
}

// --- primitives -------------------------------------------------------------
//
// The only two functions the WGSL generator does not translate: it emits
// `max`/`min` for them and checks they are still here under these names. Every
// comparison in this file goes through them, which is what keeps the rest
// ternary-free.

fn rlMax(a : f32, b : f32) -> f32 { return max(a, b); }
fn rlMin(a : f32, b : f32) -> f32 { return min(a, b); }
// --- helpers ----------------------------------------------------------------

fn rlSaturate(x : f32) -> f32 {
  return rlMin(rlMax(x, 0.0), 1.0);
}

// Analytic coverage of a signed distance under a filter of width `fw`: the
// fraction of the pixel the shape covers. This is what makes a 100 mm stripe
// legible at 200 m without a mip chain.
fn rlCoverage(d : f32, fw : f32) -> f32 {
  let h = 0.5 * rlMax(fw, 1e-6);
  return rlSaturate((h - d) / (2.0 * h));
}

// x mod period, never negative. The expression is already in [0, period) in
// exact arithmetic; the clamp is for the float edge where floor() rounds the
// wrong way and hands back a value a few ulp below zero.
fn rlWrap(x : f32, period : f32) -> f32 {
  return rlMax(x - period * floor(x / period), 0.0);
}

fn rlPaintColor(idx : f32) -> RlRgb {
  var c : RlRgb;
  c.r = 0.16; c.g = 0.46; c.b = 0.26;  // green, the last band
  if (idx < 0.5) {  // white
    c.r = 0.86; c.g = 0.86; c.b = 0.84;
  } else if (idx < 1.5) {  // yellow
    c.r = 0.83; c.g = 0.68; c.b = 0.16;
  } else if (idx < 2.5) {  // red
    c.r = 0.62; c.g = 0.16; c.b = 0.14;
  } else if (idx < 3.5) {  // blue
    c.r = 0.18; c.g = 0.30; c.b = 0.62;
  }
  return c;
}

// Dash duty with an anti-alias fallback. Below the resolution of the pattern the
// stripe fades to its duty cycle rather than aliasing between dash and gap —
// which is what stops a dashed line crawling as the camera pulls back.
fn rlDashGate(s : f32, on : f32, off : f32, fw : f32) -> f32 {
  let onLen = rlMax(on, 0.2);
  let offLen = rlMax(off, 0.2);
  let period = onLen + offLen;
  let u = rlWrap(s, period);
  let d = rlMax(-u, u - onLen);
  let c = rlCoverage(d, fw);
  let blend = rlSaturate(fw / (onLen * 0.7));
  return c + (onLen / period - c) * blend;
}

// --- the evaluator ----------------------------------------------------------
//
// `bounds` holds only the PAINTED boundaries, ordered by t, most negative first.
// Nothing here depends on that order — the bake resolved the one thing that did
// — but the sim and the export read the same array and do.
//
// `wearMask` is a 0..1 blotch field the caller supplies (see note 2 above);
// `wheel` is how close this fragment is to a wheel path, where paint wears
// fastest.
fn rlEvaluateMarkings(bounds : ptr<function, array<RlBoundary, RL_MAX_BOUNDS>>, count : i32, s : f32, t : f32, fw : f32, roadWear : f32, wearMask : f32, wheel : f32) -> RlPaint {
  var out : RlPaint;
  out.coverage = 0.0;
  out.r = 0.8;
  out.g = 0.8;
  out.b = 0.8;

  for (var i : i32 = 0; i < count; i = i + 1) {
    let style = (*bounds)[i].style;
    if (style < 0.5) { continue; }  // RL_MARK_NONE

    let bt = (*bounds)[i].t;
    let dt = t - bt;
    // Nothing is painted more than a metre from its own boundary, so most
    // fragments reject every marking on the road in one compare each.
    if (dt > 1.0 + fw || dt < -(1.0 + fw)) { continue; }

    let w = rlMax((*bounds)[i].width, 0.06);
    // Anti-shimmer: never draw a stripe thinner than the filter, and scale
    // its contribution so average brightness is preserved. Without this a
    // receding lane line sparkles instead of fading.
    let effW = rlMax(w, fw * 1.6);
    let energy = w / effW;

    let off = ((*bounds)[i].gap + w) * 0.5;
    let dash = rlDashGate(s, (*bounds)[i].dashOn, (*bounds)[i].dashOff, fw);
    var cov = 0.0;

    if (style < 1.5) {  // SOLID
      cov = rlCoverage(abs(dt) - effW * 0.5, fw);
    } else if (style < 2.5) {  // DASHED
      cov = rlCoverage(abs(dt) - effW * 0.5, fw) * dash;
    } else if (style < 3.5) {  // DOUBLE
      let a = rlCoverage(abs(dt + off) - effW * 0.5, fw);
      let b = rlCoverage(abs(dt - off) - effW * 0.5, fw);
      cov = rlMax(a, b);
    } else if (style < 4.5) {  // SOLID_DASHED
      let a = rlCoverage(abs(dt + off) - effW * 0.5, fw);
      let b = rlCoverage(abs(dt - off) - effW * 0.5, fw) * dash;
      cov = rlMax(a, b);
    } else if (style < 5.5) {  // DASHED_SOLID
      let a = rlCoverage(abs(dt + off) - effW * 0.5, fw) * dash;
      let b = rlCoverage(abs(dt - off) - effW * 0.5, fw);
      cov = rlMax(a, b);
    } else if (style < 6.5) {  // WIDE_DASHED (ramp extension)
      let on = 0.6;
      let period = 1.8;
      let u = rlWrap(s, period);
      let d = rlMax(-u, u - on);
      var g = rlCoverage(d, fw);
      g = g + (on / period - g) * rlSaturate(fw / (on * 0.7));
      let wide = rlMax(0.20, fw * 1.6);
      cov = rlCoverage(abs(dt) - wide * 0.5, fw) * g;
    } else if (style < 7.5) {  // BOTTS
      let pitch = 1.2;
      let u = rlWrap(s, pitch) - pitch * 0.5;
      cov = rlCoverage(sqrt(dt * dt + u * u) - 0.055, fw);
    } else {  // HATCH / CHEVRON
      // Areas, not lines — which is also why OpenDRIVE cannot express them
      // as a roadMark. The far edge was resolved at bake time (the bake can
      // see unpainted boundaries; the shader is only given painted ones)
      // and travels in `gap`, which the area styles do not otherwise use.
      let far = (*bounds)[i].gap;
      let lo = rlMin(bt, far);
      let hi = rlMax(bt, far);
      if (t >= lo && t <= hi) {
        let d = rlWrap((s + t) * 0.7071, 1.4) - 0.7;
        cov = rlCoverage(abs(d) - 0.07, fw);
      }
    }

    if (cov <= 1e-4) { continue; }
    cov *= energy;

    let wearAmt = rlSaturate(roadWear + (*bounds)[i].wear);
    if (wearAmt > 0.001) {
      let erode = rlSaturate((wearAmt * (0.55 + 0.9 * wheel) - wearMask + 0.35) * 2.2);
      cov *= (1.0 - 0.95 * erode);
    }

    // Painted over painted keeps the newest colour; coverage saturates.
    if (cov > out.coverage * 0.5) {
      let c = rlPaintColor((*bounds)[i].color);
      out.r = c.r;
      out.g = c.g;
      out.b = c.b;
    }
    out.coverage = rlMin(out.coverage + cov, 1.0);
  }
  return out;
}
