-- roadbed_network.lua — the FULL pipeline (ADR-0048): a road network GENERATED by the
-- engine (city.layout's terrain-aware tensor field) is converted spline->ribbon by the
-- union/roadbed and draped on the same terrain. The generators feed straight in via
-- `layout=` — each graph edge becomes a spine, half-width from its class width.

local hills = terrain.fbm{ seed = 6, freq = 0.010, amp = 12, octaves = 3 }

-- Generate a terrain-aware network (the work from earlier in this branch): the tensor
-- field bends to follow contours, steep streets are pruned, the graph stays connected.
local lay = city.layout{ pattern = "tensor", extent = 150, spacing = 48, step = 8,
                         radial_decay = 110, radial_strength = 1.2, grid_strength = 1.0,
                         terrain = hills, max_grade = 0.13, slope_align = 1.3, seed = 6 }

-- Asphalt/concrete grain (modulates the roadbed's per-band colours).
local grit  = texture.fbm{ seed = 7, scale = 40, octaves = 4 }:scale_bias(0.25, 0.82)
local grain = texture.bake_color(grit, { 0.70, 0.70, 0.72 }, { 1.0, 1.0, 1.0 }, 256)
local surf  = material.new{ albedo = grain, roughness = 0.93, tile = 7 }

-- Convert the generated splines to a merged, draped roadbed in one call.
local bed = city.roadbed{ layout = lay, cell = 0.7, sidewalk = 2.2, curb = 0.18,
                          lift = 0.06, height = hills }

local m = model.new()
m:add(terrain.mesh(hills, { size = 360, resolution = 260, color = { 0.37, 0.45, 0.28 } }))
m:add_solid(bed, surf)
return m
