# Generates the WGSL embedding header for the WebGPU backend: each
# shaders/webgpu/*.wgsl becomes a raw-string constant (kMeshWgsl, ...) in
# webgpu_shaders_gen.h, so the wasm needs no runtime shader fetch while the
# sources stay real files (highlighting, diffs, future cross-compilation).
#
# Invoked at build time (root CMakeLists.txt) whenever a .wgsl changes:
#   cmake -DSHADER_DIR=<repo>/shaders/webgpu -DOUT=<build>/generated/webgpu_shaders_gen.h
#         -P cmake/embed_wgsl.cmake
#
# The raw-string delimiter WGSL matches the one the sources were authored
# under, so shader bodies can never terminate the literal early.

set(RT_WGSL_FILES        # file basename -> constant, in embed order
    "mesh:kMeshWgsl"
    "brdf_lut:kBrdfWgsl"
    "composite:kCompositeWgsl"
    "bloom:kBloomWgsl"
    "ssao:kSsaoWgsl"
    "ssr:kSsrWgsl"
    "blit:kBlitWgsl")

set(RT_HEADER "// Generated by cmake/embed_wgsl.cmake — DO NOT EDIT.\n")
string(APPEND RT_HEADER "// Edit shaders/webgpu/*.wgsl instead.\n\n")

foreach(entry IN LISTS RT_WGSL_FILES)
    string(REPLACE ":" ";" pair "${entry}")
    list(GET pair 0 base)
    list(GET pair 1 var)
    set(path "${SHADER_DIR}/${base}.wgsl")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "embed_wgsl: missing ${path}")
    endif()
    file(READ "${path}" body)
    string(APPEND RT_HEADER "static const char ${var}[] = R\"WGSL(\n${body})WGSL\";\n\n")
endforeach()

file(WRITE "${OUT}" "${RT_HEADER}")
